<?php

namespace POL\CarnetBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ListeContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListeContactRepository extends EntityRepository
{
  public function getContactWithData($id,$idUser){
    $qb = $this->createQueryBuilder('a')
    ->leftJoin('a.contactId', 'contactId')
    ->where('contactId = :id', 'a.usernameId = :idUser')
    ->setParameters(array('id'=>$id, 'idUser'=>$idUser));

    return $qb->getQuery()->getResult();
  }

  public function getAllContact($id){
    $qb = $this->createQueryBuilder('a')
    ->leftJoin('a.contactId', 'contactId')
    ->where('a.usernameId = :id')
    ->setParameter('id', $id);
    return $qb->getQuery()->getResult();
  }

  public function checkIssetContact($id,$idUser){
    $qb = $this->createQueryBuilder('a')
    ->leftJoin('a.contactId', 'contactId')
    ->where('contactId = :id', 'a.usernameId = :idUser')
    ->setParameters(array('id'=>$id, 'idUser'=>$idUser));

    return $qb->getQuery()->getResult();
  }


}
